name: build and deploy marp to github pages

on:
  push:
    branches: [main]

env:
  MARP_CLI_VER: 1.4.0
  MARP_ARGS: presentation.md -o index.html
  PUBLISH_TO_BRANCH: gh-pages

jobs:
  build-deploy-marp:
    runs-on: ubuntu-latest
    steps:
      - name: install marp-cli via NPM
        run: |
          npm install -g @marp-team/marp-cli@${{ env.MARP_CLI_VER }}
      - name: Check out source code
        uses: actions/checkout@v2
      - name: MARP-compile to index.html
        run: |
          marp ${{ env.MARP_ARGS }}
      - name: Deploy MARP'd index.html to GitHub Pages
        run: |
          printf "Publishing to ${{ github.repository }} ${{ env.PUBLISH_TO_BRANCH}}...\n"
          printf "\n"
          remote_repo="https://x-access-token:${{ env.GITHUB_TOKEN}}@github.com/${{ github.repository }}.git" && \
          git init && \
          git config user.name "marp-action" && \
          git config user.email "marp-action@users.noreply.github.com" && \
          git add index.html && \
          git status && \
          curr_branch="$(git rev-parse --abbrev-ref HEAD)" && \
          commit_msg="${COMMIT_MSG:-'Marp Actions Build'}" && \
          git commit -m "${commit_msg}"
          git push --force $remote_repo ${curr_branch}:${{ env.PUBLISH_TO_BRANCH}}

